[theme] # Solarized
# ref: https://blog.streamlit.io/introducing-theming/

# Primary accent for interactive elements
# primaryColor = "#d33682" # Magneta
primaryColor = "#b58900" # yellow

# Background color for the main content area
# backgroundColor = "#002b36"
backgroundColor = "#586e75"

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = "#586e75"
secondaryBackgroundColor = "#002b36"

# Color used for almost all text
textColor = "#fafafa"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

# Blue & Yellow
# [theme]
# primaryColor="#fffd21"
# backgroundColor="#35729a"
# secondaryBackgroundColor="#012358"
# textColor="#fafafa"
# font="sans serif"

# inspirations:
# https://www.canva.com/learn/website-color-schemes/
# https://colorpalettes.net/tag/blue-and-yellow/

# Night Mode TWitter + Shades of Yellow
# [theme]
# primaryColor="#e9d700"
# backgroundColor="#243447"
# secondaryBackgroundColor="#141d26"
# textColor="#ffffff"
